<!DOCTYPE html>
<html lang="es">

<head>
  <title>Error login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <!-- Enlace al archivo CSS personalizado -->
  <link rel="stylesheet" href="../CSS/styles.css">
  <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
  <!-- Scripts JS -->
  <script src="../JS/darkMode.js"></script>
</head>

<!-- Recupera el valor de la clase guardada en la cookie -->
<?php
if (isset($_COOKIE['bodyClass'])) {
  $bodyClass = $_COOKIE['bodyClass'];
  ?>

  <body <?php echo 'class="dark-mode"'; ?>> <?php
} else {
  ?>

    <body>
      <?php
} ?>

    <div class="alert alert-danger alert-dismissible fade in">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Ooppsss!</strong> Algo ha ido mal......
    </div>

    <script>
      $(document).ready(function () {

        // Oculta el alert después de tres segundos
        setTimeout(function () {
          $('.alert').alert('close');
          window.location.href = "../Controllers/loginController.php";
        }, 2500);
      });
    </script>
  </body>

</html>