<?php
/**
 * @var array $advertisements
 * @var array $brands
 * @var array $vehicleTypes
 * @var int $selectedAdvertisementId
 * @var int $selectedBrandId 
 * @var int $selectedvehicleTypeId
 */
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Compra-Venta de coches</title>
    <!-- Archivos CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- JS de Bootstrap (requiere jQuery) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
        <!-- Scripts -->
    <link rel="stylesheet" href="../CSS/styles.css">
    <script src="../JS/list.js"></script> 
    <script src="../JS/optionsLogic.js"></script> 
    <script src="../JS/createElements.js"></script> 
</head>

<body>

    <?php include("../Controllers/initController.php"); ?>

    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <a class="navbar-brand" href="#">tunuevocoche.com</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Catálogo</a>
                </li>
                <li class="nav-item mr-2">
                    <a class="nav-link" href="#">Contacto</a>
                </li>
            </ul>
            <a href="#" id="oscuro" class="btn btn-dark mr-3" onclick="modoOscuro()">
                <i class="fas fa-moon"></i> Modo oscuro
            </a>
            <form class="form-inline my-2 my-lg-0 mr-auto">
                <div class="input-group">
                    <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Buscar">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link btn btn-primary mr-2 bg-light" href="logIn.phtml">Iniciar sesión</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-primary bg-light" href="signUp.phtml">Registrarse</a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Contenido principal -->

    <h1 class="text-center mb-5">Busca tu nuevo coche</h1>

    <!-- Filtro de búsqueda -->

    <div class="row ml-1" id="result">
        <div class="col-md-2 mt-4" id="searcher">
            <div class="card">
                <div class="card-header">
                    Busca tu vehículo
                </div>
                <div class="card-body">
                    <!-- <form> -->
                    <div class="form-group">
                        <label for="vehicleTypeLabel">Tipo de vehículo:</label>
                        <select class="form-control" id="vehicleType" onchange="optionValue(this.value)">
                            <option value="0" class="optionsClassName" selected>Todos los tipos</option>

                            <?php
                            foreach ($vehicleTypes as $vehicleType) { ?>
                                <option value="<?php echo $vehicleType->id ?>" class="optionsClassName">
                                    <?php
                                    echo $vehicleType->name ?>
                                </option>
                            <?php } ?>

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="brandLabel">Marca:</label>
                        <select class="form-control" id="brand" onchange="optionModelValue(this.value)">
                            <option value="0" class="optionsClassName" selected>Todas las marcas</option>

                            <?php
                            foreach ($brands as $brand) { ?>
                                <option value="<?php echo $brand->id ?>" class="optionsClassName">
                                    <?php
                                    echo $brand->name ?>
                                </option>
                            <?php } ?>

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="brandModel">Modelo:</label>
                        <select class="form-control" id="model">
                            <option value="0" class="optionsClassName" selected>Todos los modelos</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="maxPriceLabel">Precio máximo:</label>
                        <input type="number" class="form-control" id="maxPrice" step="1000" min="0" value="">
                    </div>
                    <button class="btn btn-primary" onclick="sendData()" id="buttonData">Buscar</button>
                    <!-- </form> -->
                </div>
            </div>
        </div>

        <!-- Modelos de vehículos -->

        <script>
            toListAdvertisements();            
        </script>

        <!-- <?php $counter = 0;

        foreach ($advertisements as $advertisement) {

            if ($counter > 2 && ($counter % 3 == 0)) { ?>
                <div class="col-md-2 mt-4 separator"></div>
            <?php } ?>

            <div class="col-md-3 mt-4 portada ml-3 mb-3">
                <div class="card sonDiv">
                    <img src="<?php echo $advertisement->images->foto1 ?>" class="card-img-top"
                        alt="Imagen de un <?php echo $advertisement->brand_id->name ?>">
                    <div class="card-body advertisementTextDiv">
                        <h5 class="card-title">
                            <?php echo $advertisement->brand_id->name . " " . $advertisement->model_id->name . " " . $advertisement->model_id->series ?>
                        </h5>
                        <img src="<?php echo $advertisement->brand_id->logo ?>" class="float-right photoLogo"
                            alt="Imagen del logo" <?php echo $advertisement->brand_id->name ?>>
                        <p class="card-text">
                            <?php echo $advertisement->description ?>
                        </p>
                        <h5 class="card-text price">
                            <?php echo $advertisement->price ?>
                        </h5>
                        <p class="card-text">
                            <?php echo $advertisement->motorization_id->power . "CV - " . $advertisement->model_id->engineType_id->name ?>
                        </p>
                        <p class="card-text">
                            <?php echo $advertisement->km . " km" ?>
                        </p>
                        <a href="#" class="btn btn-primary">Ver detalles</a>
                    </div>
                </div>
            </div>
            <?php $counter = $counter + 1;
        } ?> -->
    </div>  
</body>

</html>
