<?php
/**
 * @var array $advertisements
 * @var array $brands
 * @var array $vehicleTypes 
 * @var array $sellerUsers
 */
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Compra-Venta de coches</title>
    <!-- Archivos CSS de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- JS de Bootstrap (requiere jQuery) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Link FontAwesome -->
    <script src="https://kit.fontawesome.com/e83e9a2953.js" crossorigin="anonymous"></script>
    <!-- Archivos CSS -->
    <link rel="stylesheet" href="../CSS/styles.css">
    <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
    <link rel="stylesheet" href="../CSS/custom.css">

    <!-- Scripts JS -->
    <script src="../JS/list.js"></script>
    <script src="../JS/optionsLogic.js"></script>
    <script src="../JS/createElements.js"></script>
    <script src="../JS/search.js"></script>
    <script src="../JS/darkMode.js"></script>
    <script src="../JS/sortBy.js"></script>
</head>

<!-- Recupera el valor de la clase guardada en la cookie -->
<?php
if (isset($_COOKIE['bodyClass'])) {
    $bodyClass = $_COOKIE['bodyClass']; ?>

    <body class="dark-mode">
        <?php
} else { ?>

        <body>
            <?php
} ?>

        <?php
        // Guardar la clase de la etiqueta en una cookie durante una hora
        $bodyClass = 'dark-mode';
        setcookie('bodyClass', $bodyClass, time() + 0, '/');
        ?>

        <!-- <?php include("../Controllers/initController.php"); ?> -->

        <?php
        if (isset($_COOKIE['bodyClass'])) {
            $bodyClass = $_COOKIE['bodyClass']; ?>
            <nav class="navbar navbar-expand-lg dark-mode sticky-top" id="barNav">
                <?php
        } else { ?>
                <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" id="barNav">
                    <?php
        } ?>
                <a class="navbar-brand" href="#">theseeker.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Inicio</a>
                        </li>
                        <li class="nav-item active">
                            <!-- <a class="nav-link" href="#">Contacto</a> -->
                            <a type="button" class="nav-link" data-toggle="modal" data-target="#contactModal"
                                data-whatever="@getbootstrap">Contacto</a>
                        </li>
                        <li class="nav-item mr-2">
                            <select id="searchSelect" class="form-select border-0">
                                <option value="0" class="" selected>&nbsp;&nbsp;Buscar por</option>
                                <option value="1" class="">Marca</option>
                                <option value="2" class="">Modelo</option>
                                <option value="3" class="">Tipo de motor</option>
                                <option value="4" class="">Color</option>
                                <option value="5" class="">Potencia</option>
                                <option value="6" class="">Velocidad máxima</option>
                                <option value="7" class="">Aceleración</option>
                                <option value="8" class="">Consumo</option>
                                <option value="9" class="">KM</option>
                                <option value="10" class="">País</option>
                                <option value="11" class="">Año de lanzamiento</option>
                                <option value="12" class="">Precio</option>
                            </select>
                        </li>
                    </ul>
                    <form id="searchForm" class="form-inline my-2 my-lg-0 mr-auto">
                        <div class="input-group">
                            <input id="searchInput" class="form-control mr-sm-2" type="search"
                                placeholder="Pon algo aquí..." aria-label="Buscar">
                            <div class="input-group-append">
                                <button id="searchButton" class="btn btn btn-primary bg-light" type="submit"><i
                                        class="fas fa-search text-secondary"></i></button>
                            </div>
                        </div>
                    </form>

                    <?php if (!isset($_SESSION['id'])) { ?>
                        <a href="#" id="oscuro" class="btn btn-dark mr-3" data-bs-toggle="tooltip"
                            title="Tienes que loguearte para activar el modo oscuro" disabled>
                            <i class="fas fa-moon"></i> Modo oscuro </a>
                    <?php } else {
                        ?>
                        <a href="#" id="oscuro" class="btn btn-dark mr-3" onclick="setDarkMode()">
                            <i class="fas fa-moon"></i> Modo oscuro </a>
                        <?php } ?>



                        <ul class="navbar-nav" id="registerButtons">
                            <li class="nav-item">
                                <?php if (!isset($_SESSION["mail"])) { ?>
                                    <a class="nav-link btn btn-primary ml-2 bg-light"
                                        href="../Controllers/signUpController.php" id="signUpLink">Registrarse</a>
                                <?php } else { ?>
                                    <div style="position: absolute; top: 60px; right:10px">

                                        <h6 class="text-right"><span>
                                                <?php

                                                if (isset($_SESSION['mail'])) {
                                                    foreach ($sellerUsers as $sellerUser) {
                                                        if ($sellerUser->user_app_id->id == $_SESSION['id']) {
                                                            $mailSession = $sellerUser->user_app_id->mail;
                                                            $idSession = $sellerUser->id;
                                                        } else {
                                                            $mailSession = $_SESSION['mail'];
                                                            $idSession = $_SESSION['id'];
                                                        }
                                                    }
                                                    $intSession = intval($_SESSION["id"]);
                                                    $intSellerUserAppId = intval($sellerUser->user_app_id->id);

                                                }
                                                if ($intSession == $intSellerUserAppId) { ?>
                                                    <?php echo 'Seller User: ' . $mailSession ?>
                                                <?php } else { ?>
                                                    <?php echo 'Logueado como: ' . $mailSession ?>
                                                <?php } ?>
                                            </span>
                                        </h6>
                                    </div>
                                <?php } ?>
                            </li>
                            <li class="nav-item">
                                <?php if (!isset($_SESSION["mail"])) { ?>
                                    <a class="nav-link btn btn-primary ml-2 bg-light"
                                        href="../Controllers/loginController.php" id="loginLink">Iniciar
                                        sesión</a>
                                <?php } else { ?>
                                    <a class="nav-link btn btn-primary ml-2 bg-light"
                                        href="../Controllers/logoutController.php" id="loginLink">Cerrar
                                        sesión</a>
                                <?php } ?>
                            </li>
                            <li class="nav-item">
                                <?php
                                if (isset($_SESSION["mail"])) {

                                    if ($intSession == intval($sellerUser->user_app_id->id)) { ?>

                                        <a class="nav-link btn btn-primary ml-2 bg-light"
                                            href="../Controllers/insertAdvertisementController.php" id="sellYourCar">Vende tu
                                            coche</a>
                                    <?php } else { ?>
                                        <a class="nav-link btn btn-primary ml-2 bg-light"
                                            href="../Controllers/sellerSignUpController.php" id="sellYourCar">Vende tu
                                            coche</a>
                                    <?php }
                                } ?>
                            </li>
                        </ul>
                </div>
            </nav>

            <!-- Modal para el contacto -->
            <div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="contactModalLabel">Contacta</h5>
                        </div>

                        <?php

                        if (isset($_SESSION['mail']) != null) { ?>

                            <div class="modal-body">
                                <form id="emailForm">
                                    <div class="form-group">
                                        <label for="emailSender-name" class="col-form-label"
                                            name="emailSender-name">De:</label>
                                        <h5 type="email" id="recipient">
                                            <?php echo $_SESSION["mail"] ?>
                                        </h5>
                                    </div>
                                    <div class="form-group">
                                        <label for="recipient-name" class="col-form-label"
                                            name="recipient-name">para:</label>
                                        <h4>theseeker.com</h4>
                                    </div>
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label" name="message-text">Asunto:</label>
                                        <input class="form-control" id="message-text" type="text" id="subject"
                                            placeholder="Asunto"></input>
                                    </div>
                                    <div class="form-group">
                                        <label for="message-text" class="col-form-label"
                                            name="message-text">Mensaje:</label>
                                        <textarea class="form-control" id="message" placeholder="Mensaje"></textarea>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary bg-light text-secondary"
                                            data-dismiss="modal">Cerrar</button>
                                        <button type="submit" class="btn btn-primary bg-light text-secondary"
                                            data-toggle="modal">Enviar</button>
                                    </div>
                                </form>
                            </div>

                        <?php } else { ?>

                            <div class="modal-body">
                                <h3 class="mb-4">Debes estar registrado para poder contactar</h3>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary bg-light text-secondary"
                                    data-dismiss="modal">Cerrar</button>
                            </div>
                        <?php } ?>

                    </div>
                </div>
            </div>

            <!-- Contenido principal -->

            <h1 class="text-center mb-5 mt-5" id="title"> Bienvenido a theseeker.com</h1>

            <div class="btn-group d-flex justify-content-between mb-3">
                <div class="nav-item ml-auto">
                    <button id="sortByIndicator" class="btn btn-outline-0 text-dark" disabled>Ordenar por... </button>
                </div>
                <div class="nav-item">
                    <button id="sortByBrandNameId" class="btn btn-outline-0 sort me-5 ms-2 sortByButton"
                        onclick="sortByBrandName()">Marca</button>
                </div>
                <div class="nav-item">
                    <button id="sortByPriceAscId" class="btn btn-outline-0 me-5 sortByButton"
                        onclick="sortByPriceAsc()">Precio
                        <i class="fas fa-arrow-up"></i></button>
                </div>
                <div class="nav-item">
                    <button id="sortByPriceDescId" class="btn btn-outline-0 me-5 sortByButton"
                        onclick="sortByPriceDesc()">Precio
                        <i class="fas fa-arrow-down"></i></button>
                </div>
                <div class="nav-item">
                    <button id="sortByPowerIdAsc" class="btn btn-outline-0 me-5 sortByButton"
                        onclick="sortByPowerAsc()">Potencia <i class="fas fa-arrow-up"></i></button>
                </div>
                <div class="nav-item">
                    <button id="sortByPowerIdDesc" class="btn btn-outline-0 me-5 sortByButton"
                        onclick="sortByPowerDesc()">Potencia
                        <i class="fas fa-arrow-down"></i></button>
                </div>
                <div class="nav-item mr-auto">
                    <button id="sortByKmId" class="btn btn-outline-0 me-5 sortByButton"
                        onclick="sortByKm()">Kilómetros</button>
                </div>
            </div>


            <!-- Filtro de búsqueda -->

            <div class="row ml-1 mb-4" id="result">
                <div class="col-md-2 mt-4" id="searcher">
                    <?php
                    if (isset($_COOKIE['bodyClass'])) {
                        $bodyClass = $_COOKIE['bodyClass']; ?>
                        <div class="card dark-mode" id="cardSearcher">
                            <?php
                    } else { ?>
                            <div class="card" id="cardSearcher">
                                <?php

                    } ?>
                            <div class="card-header">
                                Busca tu vehículo
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="vehicleTypeLabel">Tipo de vehículo:</label>
                                    <select class="form-control" id="vehicleType" onchange="optionValue(this.value)">
                                        <option value="0" class="optionsClassName" selected>Todos los tipos</option>

                                        <?php
                                        foreach ($vehicleTypes as $vehicleType) { ?>
                                            <option value="<?php echo $vehicleType->id ?>" class="optionsClassName">
                                                <?php
                                                echo $vehicleType->name ?>
                                            </option>
                                        <?php } ?>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="brandLabel">Marca:</label>
                                    <select class="form-control" id="brand" onchange="optionModelValue(this.value)">
                                        <option value="0" class="optionsClassName" selected>Todas las marcas
                                        </option>

                                        <?php
                                        foreach ($brands as $brand) { ?>
                                            <option value="<?php echo $brand->id ?>" class="optionsClassName">
                                                <?php
                                                echo $brand->name ?>
                                            </option>
                                        <?php } ?>

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="brandModel">Modelo:</label>
                                    <select class="form-control" id="model">
                                        <option value="0" class="optionsClassName" selected>Todos los modelos
                                        </option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="maxPriceLabel">Precio máximo:</label>
                                    <input type="number" class="form-control" id="maxPrice" step="1000" min="0"
                                        max="100000000" value="">
                                </div>
                                <button class="btn btn-primary" onclick="sendData()" id="buttonData">Buscar</button>
                            </div>
                        </div>
                    </div>

                    <!-- Carrusel / Modelos de vehículos -->

                    <div class="row mt-4 ms-5 col-md-8 carouselClass" id="containerCarousel">
                        <div class="col-md-10 ms-5">
                            <div id="carouselId" class="carousel slide carousel-fade ms-5" data-bs-ride="carousel">
                                <div class="carousel-inner">

                                    <!-- <?php shuffle($advertisements); ?> -->
                                    <div class="carousel-item active" data-bs-interval="3000">
                                        <img src="<?php echo $advertisements[0]->images->foto1 ?>"
                                            class="d-block w-100 carouselImg" alt="...">
                                    </div>

                                    <?php for ($i = 0; $i < count($advertisements); $i++) { ?>
                                        <div class="carousel-item" data-bs-interval="3000">
                                            <img src="<?php echo $advertisements[$i + 1]->images->foto1 ?>"
                                                class="d-block w-100 carouselImg" alt="...">
                                        </div>
                                    <?php } ?>
                                </div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carouselId"
                                    data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <button class="carousel-control-next" type="button" data-bs-target="#carouselId"
                                    data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <footer class="footer mt-5 pt-2" id="footer">
                <div class="container text-center">
                    <a class="cc-facebook btn btn-link" href=https://www.facebook.com/" target="_blank"><i
                            class="fa fa-facebook fa-2x " aria-hidden="true"></i></a>
                    <a class="cc-twitter btn btn-link " href="https://twitter.com/?lang=es" target="_blank"><i
                            class="fa fa-twitter fa-2x " aria-hidden="true"></i></a>
                    <a class="cc-google-plus btn btn-link" href="https://www.tiktok.com/es/" target="_blank"><i
                            class="fa-brands fa-tiktok fa-2x" aria-hidden="true"></i></a>
                    <a class="cc-instagram btn btn-link" href="https://www.instagram.com/" target="_blank"><i
                            class="fa fa-instagram fa-2x " aria-hidden="true"></i></a>
                </div>
                <div class="text-center text-muted">
                    <p>&copy; theseeker.com. All rights reserved.<br>Design in Palma</p>
                </div>
            </footer>

    </body>

</html>