<?php
/**
 * @var array $advertisements
 * @var array $brands
 * @var array $vehicleTypes 
 * @var array $countries 
 * @var array $engineTypes 
 * @var array $models 
 */
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Insert de nuevo anuncio</title>
    <!-- Archivos CSS de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- JS de Bootstrap (requiere jQuery) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- Scripts JS -->
    <script src="../JS/list.js"></script>
    <script src="../JS/optionsLogic.js"></script>
    <script src="../JS/createElements.js"></script>
    <script src="../JS/darkMode.js"></script>
    <script src="../JS/createElements.js"></script>
</head>


<body>
    <?php include("../Controllers/listController.php"); ?>

    <?php
    // Guarda la URL en una variable de sesión
    $_SESSION['url'] = 'http://localhost/php/PROYECTO/front/Controllers/insertAdvertisementController.php';

    ?>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" data-backdrop="static"
        aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document" data-backdrop="static">

            <!-- Modal content-->
            <div class="modal-content mt-0">
                <div class="modal-header">
                    <h3 class="modal-title" id="modalTitleId" style="margin-left: 40%;">PUBLICAR ANUNCIO</h3>
                </div>
                <div class="modal-body">
                    <form action=" ../../back/Controllers/insertAdvertisementController.php" method="POST"
                        id="insertForm">
                        <div class="container-fluid">
                            <div class="card-body">
                                <input type="text" id="idUser" name="idUser" class="invisible" style="height: 1px;"
                                    placeholder="<?php echo $_SESSION['id'] ?>">
                                <!-- VEHICLETYPE -->
                                <div class="row">
                                    <div class="form-group col-md-3">
                                        <label for="vehicleTypeLabel">Tipo de vehículo</label>
                                        <select class="form-control" id="vehicleType" onchange="optionValue(this.value)"
                                            data-info="3" name="vehicleTypeName" required>
                                            <option value="0" class="optionsClassName" selected>Selecciona una opción
                                            </option>
                                            <?php
                                            foreach ($vehicleTypes as $vehicleType) {
                                                $selected = isset($_SESSION['vehicleType']) && $_SESSION['vehicleType'] == $vehicleType->id ? 'selected' : '';
                                                ?>
                                                <option value="<?php echo $vehicleType->id ?>" class="optionsClassName"
                                                    <?php echo $selected ?>>
                                                    <?php echo $vehicleType->name ?>
                                                </option>
                                            <?php } ?>

                                        </select>
                                    </div>
                                    <!-- ENGINETYPE -->
                                    <div class="form-group col-md-3">
                                        <label for="engineTypeLabel">Tipos de motor</label>
                                        <select class="form-control" id="engineType" name="selectEngineType" required>
                                            <option value="0" class="optionsClassName" selected>
                                                Selecciona una opción
                                                <?php
                                                foreach ($engineTypes as $engineType) { ?>
                                                <option value="<?php echo $engineType->id ?>" class="optionsClassName">
                                                    <?php
                                                    echo $engineType->name ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <!-- COUNTRY -->
                                    <div class="form-group col-md-3">
                                        <label for="countryLabel">País</label>
                                        <select class="form-control" id="country" name="selectCountry"
                                            onchange="toggleTextField('country', 'newCountry')" required>
                                            <option value="0" class="optionsClassName" selected>Selecciona una opción
                                            </option>
                                            <option value="-1" class="optionsClassName"
                                                style="color:white;font-weight:bold; background-color: #62cf79">Nuevo
                                                registro
                                            </option>
                                            <?php
                                            foreach ($countries as $country) { ?>
                                                <option value="<?php echo $country->id ?>" class="optionsClassName">
                                                    <?php
                                                    echo $country->name ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="newCountryLabel">Insert país:</label>
                                        <input type="text" id="newCountry" name="newCountryName" class="rounded"
                                            style="height: 38px; width: 100%" disabled>
                                    </div>
                                </div>
                                <!-- BRANDS -->
                                <div class="row mt-4">
                                    <div class="form-group col-md-3">
                                        <label for="brandLabel">Marca</label>
                                        <select class="form-control" id="brand" data-info="5"
                                            onchange="optionModelValue(this.value)" name="selectBrand" required>
                                            <script>
                                                let select = document.getElementById('brand');
                                                select.addEventListener('change', toggleTextFieldBrand);                       
                                            </script>

                                            <option value="0" class="optionsClassName" selected>Selecciona una opción
                                            </option>
                                            <option value="-1" class="optionsClassName"
                                                style="color:white;font-weight:bold; background-color: #62cf79">
                                                Nuevo
                                                registro
                                            </option>
                                            <?php
                                            foreach ($brands as $brand) { ?>
                                                <option value="<?php echo $brand->id ?>" class="optionsClassName">
                                                    <?php
                                                    echo $brand->name ?>
                                                </option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Insert brand</label>
                                        <input type="text" id="newBrand" name="newBrandName" class="rounded"
                                            style="height: 38px; width: 100%" disabled>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Insert logo file name</label>
                                        <input type="text" id="newLogoId" name="newLogoName" class="rounded"
                                            style="height: 38px; width: 100%" disabled>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newLogoLabel">Insert logo</label>
                                        <a href="../Views/loadLogoView.phtml" id="loadLogo"
                                            class="btn btn-outline-warning btn btn-block disabled text-dark"
                                            role="button" aria-disabled="true" name="logoName" target="_blank">cargar
                                            imagen de logo</a>
                                    </div>
                                </div>
                                <!-- MODEL -->
                                <div class="row mt-4">
                                    <div class="form-group col-md-3">
                                        <label for="brandModel">Modelo</label>
                                        <select class="form-control" id="model" name="modelSelect" required>
                                            <option value="0" class="optionsClassName" selected>Selecciona una opción
                                            </option>
                                            <option value="-1" class="optionsClassName"
                                                style="color:white;font-weight:bold; background-color: #62cf79">Nuevo
                                                registro
                                            </option>
                                            <script>document.getElementById('model').addEventListener('change', toggleTextFieldModel)</script>
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newModelLabel">Insert model</label>
                                        <input type="text" id="newModel" name="newModelName" class="rounded"
                                            style="height: 38px; width: 100%" disabled>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="series">Serie</label>
                                        <input type="text" id="series" name="seriesName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="release_year">Fecha de matriculación:</label>
                                        <input type="date" id="release_yearId" name="releaseYearName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                </div>
                                <!-- MOTORIZATION -->
                                <div class="row mt-4">
                                    <div class="form-group col-md-3">
                                        <label for="displacement">Cilindrada</label>
                                        <input type="text" id="displacement" name="displacementName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="power">Potencia</label>
                                        <input type="text" id="power" name="powerName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <!-- BENEFITS -->
                                    <div class="form-group col-md-3">
                                        <label for="maxVelocity">Velocidad máxima</label>
                                        <input type="text" id="maxVelocity" name="maxVelocityName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="acceleration">Aceleración de 0 a 100</label>
                                        <input type="text" id="acceleration" name="accelerationName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-md-3">
                                        <label for="consumption">Consumo</label>
                                        <input type="text" id="consumption" name="consumptionName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <!-- ADVERTISEMENT -->
                                    <div class="col-md-3">
                                        <label for="description">Descripción</label>
                                        <textarea id="description" name="descriptionName" maxlength="100"
                                            class="rounded" style="height: 38px; width: 100%" required></textarea>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="price">Precio</label>
                                        <input type="number" id="price" name="priceName" step="1000" min="0"
                                            max="100000000" class="rounded" style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="color">Color</label>
                                        <input type="text" id="color" name="colorName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-md-3">
                                        <label for="km">Kilómetros:</label>
                                        <input type="number" id="km" name="kmName" step="1000" min="0" max="1000000"
                                            class="rounded" style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="latitude">Latitud:</label>
                                        <input type="text" id="latitude" name="latitudeName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="longitude">Longitud:</label>
                                        <input type="text" id="longitude" name="longitudeName" class="rounded"
                                            style="height: 38px; width: 100%" required>
                                    </div>
                                    <!-- MULTIMEDIA -->
                                    <div class="col-md-3">
                                        <label for="newPhotoLabel">Insertar imágenes</label>
                                        <a href="../Views/loadMultimediaView.phtml" id="loadMultimedia"
                                            class="btn btn-outline-warning btn btn-block text-dark" role="button"
                                            aria-disabled="true" target="_blank">Cargar imágenes</a>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class=" col-md-3">
                                        <label for="newBrandLabel">Image 1 file name</label>
                                        <input type="text" id="newImage1" name="newImage1" class="rounded"
                                            style="height: 38px; width: 100%">
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Image 2 file name</label>
                                        <input type="text" id="newImage2" name="newImage2" class="rounded"
                                            style="height: 38px; width: 100%">
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Image 3 file name</label>
                                        <input type="text" id="newImage3" name="newImage3" class="rounded"
                                            style="height: 38px; width: 100%">
                                    </div>
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Image 4 file name</label>
                                        <input type="text" id="newImage4" name="newImage4" class="rounded"
                                            style="height: 38px; width: 100%">
                                    </div>
                                </div>
                                <div class="row mt-4 pb-4" style="border-bottom: 1px solid #d3d3d3;">
                                    <div class="col-md-3">
                                        <label for="newBrandLabel">Image 5 file name</label>
                                        <input type="text" id="newImage5" name="newImage5" class="rounded"
                                            style="height: 38px; width: 100%">
                                    </div>                                    
                                </div>
                            </div>

                        </div>
                        <div class="row mt-2">
                            <div class="col-md-12">
                                <input class="btn btn-outline-warning col-md-2 me-5" type="Reset" value="Reset">
                                <input id="closeButtonInsertView" class="close btn btn-outline-danger col-md-2 ms-2"
                                    type="button" value="Cancelar" data-dismiss="modal">
                                <input class="btn btn-outline-success col-md-7 mx-auto" type="submit" value="Insertar">
                            </div>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#myModal').modal('show');
        });

        // Reedirige a la pantalla de inicio
        document.getElementById("closeButtonInsertView").addEventListener("click", function () {
            window.location.href = "../Controllers/initController.php";
        });

    </script>
</body>

</html>