<!DOCTYPE html>
<html lang="es">

<head>
  <title>Success login</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <!-- Enlace al archivo CSS personalizado -->
  <link rel="stylesheet" href="../CSS/styles.css">
  <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
  <!-- Scripts JS -->
  <script src="../JS/darkMode.js"></script>
</head>

<body>
  <div class="alert alert-success alert-dismissible fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>¡Excelente!</strong> Auncio insertado correctamente.
  </div>

  <script>
    $(document).ready(function () {

      // Oculta el alert después de tres segundos
      setTimeout(function () {
        $('.alert').alert('close');
        window.location.href = "../Controllers/initController.php";
      }, 2500);
    });
  </script>
</body>

</html>