<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <title>Cargar imagen</title>
  <!-- Archivos CSS de Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- JS de Bootstrap (requiere jQuery) -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <!-- Archivos CSS -->
  <link rel="stylesheet" href="../CSS/insertAdvertisemetModalStyles.css">
  <!-- Scripts JS -->
  <script src="../JS/list.js"></script>
  <script src="../JS/optionsLogic.js"></script>
  <script src="../JS/createElements.js"></script>
  <script src="../JS/darkMode.js"></script>
  <script src="../JS/createElements.js"></script>
</head>

<body>
  <!-- Modal -->
  <div class="modal fade" id="modalInsertLogoId" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog" role="document" data-backdrop="static">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left: 25%">Imagen para el logo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="../php/saveLogoFile.php" method="post" enctype="multipart/form-data">
            <div class="col-md-12">
              <input type="file" name="logoFile" class="rounded" style="height: 38px; width: 100%; color:red;">
            </div>
            <div class="col-md-12 mt-4">
              <input type="submit" value="Subir archivo" class="rounded" style="height: 38px; width: 100%">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function () {
      $('#modalInsertLogoId').modal('show');
    });

    //Cierra la ventana la hacer click en el icono "close"
    let closeButton = document.querySelector('.close');

    closeButton.addEventListener('click', function () {
      // Cerrar la ventana actual
      window.location.href = 'http://localhost/php/PROYECTO/front/Views/loadLogoView.phtml';
      window.close();

    });
  </script>
</body>

</html>