<!DOCTYPE html>
<html lang="es">

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
  <div class="alert alert-success alert-dismissible fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>¡Excelente!</strong> Te has logueado correctamente.
  </div>

  <script>
    $(document).ready(function () {
      // Muestra un alert de Bootstrap con un mensaje.
      $('<div class="alert alert-success alert-dismissible fade in" role="alert"><button type="button" class="close" data-dismiss="alert">&times;</button><strong>Bienvenido/a a nuestro sitio web</strong></div>').appendTo('#messages');

      // Oculta el alert después de tres segundos
      setTimeout(function () {
        $('.alert').alert('close');
        window.location.href = "../Controllers/initController.php";
      }, 2500);
    });
  </script>
</body>

</html>