<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión</title>
    <!-- Enlace al archivo CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Enlace al archivo CSS personalizado -->
    <link rel="stylesheet" href="CSS/signUplogInStyles.css">
    <!-- Enlace al archivo JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div style="display: flex; align-items: baseline; justify-content: center; height: 100vh;" class="verticalPosition">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4">
                    <div class="bg-info">
                        <h1 class="text-center">Iniciar sesión</h1>
                        <form>
                            <div class="form-group">
                                <label for="email">Correo electrónico:</label>
                                <input type="email" class="form-control" id="email"
                                    placeholder="Ingrese su correo electrónico">
                            </div>
                            <div class="form-group">
                                <label for="password">Contraseña:</label>
                                <input type="password" class="form-control" id="password"
                                    placeholder="Ingrese su contraseña">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Iniciar sesión</button>
                        </form>
                        <p class="text-center">¿No tienes una cuenta? <a href="signUp.html">Registrarse</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>