<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse</title>
    <!-- Enlace al archivo CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- JS de Bootstrap (requiere jQuery) -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Enlace al archivo CSS personalizado -->
    <link rel="stylesheet" href="../CSS/styles.css">
    <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
    <!-- Scripts JS -->
    <!-- <script src="../JS/darkMode.js"></script> -->
</head>

<body>

    <div class="container">
        <div class="row verticalPosition">
            <div class="col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4 mx-auto">
                <div class="bg-info">
                    <h1 class="text-center">Registrarse</h1>
                    <form method="post">
                        <div class="form-group">
                            <label for="email">Correo electrónico:</label>
                            <input type="email" id="mail" class="form-control" name="mail"
                                placeholder="Ingrese su correo electrónico">
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña:</label>
                            <input type="password" id="password" class="form-control" name="password"
                                placeholder="Ingrese su contraseña">
                        </div>
                        <div class="form-group">
                            <label for="confirm-password">Confirmar contraseña:</label>
                            <input type="password" id="password2" class="form-control" name="password2"
                                placeholder="Confirme su contraseña">
                        </div>
                        <input type="submit" class="btn btn-primary btn-block" value="Registrarse">
                    </form>
                    <p class="text-center">¿Ya tienes una cuenta? <a href="../Controllers/loginController.php">Iniciar
                            sesión</a></p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>