<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse</title>
    <!-- Enlace al archivo CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Enlace al archivo CSS personalizado -->
    <link rel="stylesheet" href="CSS/signUplogInStyles.css">
    <!-- Enlace al archivo JavaScript de Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row verticalPosition">
            <div class="col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4">
                <div class="bg-info">
                    <h1 class="text-center">Registrarse</h1>
                    <form>
                        <div class="form-group">
                            <label for="nombre">Nombre completo:</label>
                            <input type="text" class="form-control" id="nombre" placeholder="Ingrese su nombre">
                        </div>
                        <div class="form-group">
                            <label for="email">Correo electrónico:</label>
                            <input type="email" class="form-control" id="email"
                                placeholder="Ingrese su correo electrónico">
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña:</label>
                            <input type="password" class="form-control" id="password"
                                placeholder="Ingrese su contraseña">
                        </div>
                        <div class="form-group">
                            <label for="confirm-password">Confirmar contraseña:</label>
                            <input type="password" class="form-control" id="confirm-password"
                                placeholder="Confirme su contraseña">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                    </form>
                    <p class="text-center">¿Ya tienes una cuenta? <a href="logIn.html">Iniciar sesión</a></p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>