<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse</title>
    <!-- Enlace al archivo CSS de Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- JS de Bootstrap (requiere jQuery) -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Enlace al archivo CSS personalizado -->
    <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
    <!-- Scripts JS -->
    <!-- <script src="../JS/darkMode.js"></script> -->
</head>

<body>

    <?php include("../Controllers/listController.php"); ?>

    <div class="container verticalPosition seller">
        <div class="row">
            <div class="col-sm-8 col-md-6 col-lg-4 col-sm-offset-2 col-md-offset-3 col-lg-offset-4 mx-auto">
                <div class="divForm">
                    <h1 class="text-center">Registro de vendedor</h1>
                    <form method="post" class="mb-2">
                        <div class="form-group">
                            <label for="name">Nombre:</label>
                            <input type="text" id="nameSurname" class="form-control" name="nameSurname"
                                placeholder="Nombre y apellidos">
                        </div>
                        <div class="form-group">
                            <label for="nif">NIF:</label>
                            <input type="text" id="nif" class="form-control" name="nif"
                                placeholder="Documento de identidad">
                        </div>
                        <div class="form-group">
                            <label for="phoneNumber">Teléfono:</label>
                            <input type="text" id="phoneNumber" class="form-control" name="phoneNumber"
                                placeholder="Teléfono">
                        </div>
                        <input type="text" id="mail" class="form-control invisible" name="mail"
                            value="<?php echo $_SESSION['mail'] ?>">
                        <input type="text" id="idUser" class="form-control invisible " name="id"
                            value="<?php echo $_SESSION['id'] ?>">
                        <input type="submit" class="btn btn-outline-success btn-block send" value="Registrarse">
                    </form>
                    <p>
                        <a href='../Controllers/initController.php' class="text-secondary">Volver a la página
                            principal</a>
                    </p>
                </div>

            </div>
        </div>
    </div>
</body>

</html>