<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detalle del coche</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css">
  <!-- Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.min.js"></script>
  <!-- CSS -->
  <link rel="stylesheet" href="../CSS/signUplogInStyles.css">
  <link rel="stylesheet" href="../CSS/styles.css">
</head>

<body>
  <div class="container mt-5">
    <h1>Detalle del coche</h1>
    <div class="row mb-5">
      <div class="col-md-7">
        <div class="card">
          <img src="../images/advertisementImages/subaru-wrx-2021-7166_18.jpg" class="card-img-top"
            alt="Imagen del coche">
        </div>
      </div>
      <div class="col-md-5">
        <div class="card ms-4">
          <div class="card-body p-0">
            <div class="iframe-container">
              <iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                src="https://maps.google.com/maps?q=39.5696,2.6502 &hl=es&z=10&output=embed"></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 mt-2">
        <div class="card">
          <!-- <div class="card-header">
            Nombre del coche
          </div> -->
          <div class="card-body">
            <h2>Nombre del coche</h2>
            <p><strong>Marca:</strong>`${$advertisement[1].id}`</p>
            <p><strong>Modelo:</strong> Nombre del modelo</p>
            <p><strong>Año:</strong> Año del coche</p>
            <p><strong>Descripción:</strong> Descripción detallada del coche</p>
            <p><strong>Precio:</strong> Precio del coche</p>
            <p><strong>km:</strong> Precio del coche</p>
            <p><strong>Color:</strong> Precio del coche</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mt-2">
        <div class="card">
          <!-- <div class="card-header">
            Prestaciones
          </div> -->
          <div class="card-body">
            <h2>Características</h2>
            <p><strong>Motor:</strong> Nombre de la marca</p>
            <p><strong>Consumo:</strong> Nombre de la marca</p>
            <p><strong>Velocidad máxima:</strong> Nombre de la marca</p>
            <p><strong>Aceleración:</strong> Nombre de la marca</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 mt-5">
        <div class="card">
          <!-- <div class="card-header">
            Contacta con el vendedor
          </div> -->
          <div class="card-body">
            <p>Para contactar con el vendedor, envía un correo electrónico a:</p>
            <a href="mailto:vendedor@example.com"
              class="btn btn-primary bg-light text-secondary">vendedor@example.com</a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <h2 id="galleryH2" class="mt-5 mb-5">Galería de imágenes</h2>
      <section class=" col-md-12">
        <img src="../images/advertisementImages/FERRARI-488-Pista-6247_2.jpg" alt="">
        <img src="../images/advertisementImages/FERRARI-488-Pista-6247_3.jpg" alt="">
        <img src="../images/advertisementImages/FERRARI-488-Pista-6247_4.jpg" alt="">
        <img src="../images/advertisementImages/FERRARI-488-Pista-6247_6.jpg" alt="">
        <img src="../images/advertisementImages/FERRARI-488-Pista-6247_7.jpg" alt="">
      </section>
    </div>

    <!-- <div class="row mt-5">
      <div class="col-md-12">
        <h2>Otras imágenes del coche</h2>
        <div id="carouselId" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="../images/advertisementImages/FERRARI-488-Pista-6247_2.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="../images/advertisementImages/FERRARI-488-Pista-6247_3.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="../images/advertisementImages/FERRARI-488-Pista-6247_4.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="../images/advertisementImages/FERRARI-488-Pista-6247_6.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
              <img src="../images/advertisementImages/FERRARI-488-Pista-6247_7.jpg" class="d-block w-100" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselId"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselId"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div> -->
  </div>
</body>

</html>